import { Job } from "@/lib/types";

export const jobsData: Job[] = [
  {
    id: "j1",
    title: "Frontend Engineer",
    company: "Turing Labs",
    salary: "INR 18L - 24L",
    location: "Bengaluru, India",
    source: "LinkedIn",
    sourceUrl: "https://www.linkedin.com/jobs",
    skills: ["react", "next.js", "typescript", "tailwind", "testing"],
    type: ["Full Time", "Remote"],
    region: "India",
    stateOrContinent: "Karnataka",
  },
  {
    id: "j2",
    title: "UI Engineer",
    company: "PixelForge",
    salary: "INR 12L - 16L",
    location: "Pune, India",
    source: "Naukri",
    sourceUrl: "https://www.naukri.com",
    skills: ["figma", "react", "css", "accessibility", "storybook"],
    type: ["Full Time"],
    region: "India",
    stateOrContinent: "Maharashtra",
  },
  {
    id: "j3",
    title: "Product Engineer",
    company: "Northwave",
    salary: "USD 70k - 95k",
    location: "Berlin, Germany",
    source: "Indeed",
    sourceUrl: "https://www.indeed.com",
    skills: ["react", "node", "graphql", "typescript", "docker"],
    type: ["Full Time"],
    region: "International",
    stateOrContinent: "Europe",
  },
  {
    id: "j4",
    title: "Frontend Internship",
    company: "CyanWorks",
    salary: "INR 30k / month",
    location: "Remote, India",
    source: "LinkedIn",
    sourceUrl: "https://www.linkedin.com/jobs",
    skills: ["html", "css", "javascript", "react", "git"],
    type: ["Internship", "Remote"],
    region: "India",
    stateOrContinent: "Delhi",
  },
  {
    id: "j5",
    title: "Remote UI Developer",
    company: "Align Partners",
    salary: "USD 50k - 72k",
    location: "Toronto, Canada",
    source: "Wellfound",
    sourceUrl: "https://wellfound.com/jobs",
    skills: ["next.js", "tailwind", "animations", "typescript", "ux"],
    type: ["Remote", "Part Time"],
    region: "International",
    stateOrContinent: "North America",
  },
  {
    id: "j6",
    title: "React Developer",
    company: "Signal Stack",
    salary: "INR 9L - 14L",
    location: "Hyderabad, India",
    source: "Naukri",
    sourceUrl: "https://www.naukri.com",
    skills: ["react", "redux", "typescript", "rest", "jest"],
    type: ["Full Time"],
    region: "India",
    stateOrContinent: "Telangana",
  },
];

export const indianStates = [
  "All",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const continents = ["All", "Asia", "Europe", "North America", "South America", "Africa", "Oceania"];
